apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://zabbix-community.github.io/helm-zabbix
    chart: zabbix
    targetRevision: 7.0.12
    helm:
      values: |
        zabbixWeb:
          service:
            type: LoadBalancer
            port: 8080
        zabbixServer:
          service:
            type: LoadBalancer
            port: 8081
        zabbixAgent:
          ZBX_ACTIVE_ALLOW: true
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true
